[project]
name = "brats-submission-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "contourpy==1.3.2",
    "networkx==3.4.2",
    "numpy==1.26.4",
    "scipy==1.15.3",
    "tifffile==2025.5.10",
]
